services:
  app:
    image: ghcr.io/fdcir3tt/app
    pull_policy: always
    restart: unless-stopped
    container_name: dashboard
    volumes:
      - ./dashboard:/app/dashboard
      - ./dashboard.py:/app/dashboard.py
      - ./assets:/app/assets
      - ./data:/app/data:z
      - ./log/:/app/log:z
    env_file:
      - ./.env
    ports:
      - 8501:8501
    networks:
      - dashboard-net
    mem_limit: 5g
    memswap_limit: 7g


networks:
  dashboard-net:
    external: true