# Experiment Config
model_type: ARIMA
dataset: HERMOSILLO, SON_PAPXRX080
metrics:
  - mae
  - mfe
  - rmse
  - da
parameters:
  p: 3
  d: 1
  q: 2
training_data_start_date: "2025-09-01"
training_data_end_date: "2026-03-30"
frequency: "daily"
horizon: 30
training_window: 180
seed: 12
git_commit: null
feature_set: raw




