CREATE DATABASE dashboard_app_db;
CREATE USER admin_user WITH PASSWORD 'foo';

\c dashboard_app_db

CREATE SCHEMA raw AUTHORIZATION admin_user;
CREATE SCHEMA staging AUTHORIZATION admin_user;
CREATE SCHEMA etl AUTHORIZATION admin_user;
CREATE SCHEMA marts AUTHORIZATION admin_user;

GRANT USAGE, CREATE ON SCHEMA raw TO admin_user;
GRANT USAGE, CREATE ON SCHEMA staging TO admin_user;
GRANT USAGE, CREATE ON SCHEMA etl TO admin_user;
GRANT USAGE, CREATE ON SCHEMA marts TO admin_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA staging
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA etl
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA marts
GRANT ALL ON TABLES TO admin_user;