CREATE DATABASE dashboard_app_db;
CREATE USER admin_user WITH PASSWORD 'foo';

\c dashboard_app_db

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA raw AUTHORIZATION admin_user;
CREATE SCHEMA staging AUTHORIZATION admin_user;
CREATE SCHEMA etl AUTHORIZATION admin_user;
CREATE SCHEMA marts AUTHORIZATION admin_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA raw
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA staging
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA etl
GRANT ALL ON TABLES TO admin_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA marts
GRANT ALL ON TABLES TO admin_user;